issuer: http://127.0.0.1:5556/dex

# storageにはmemory, sqlite
storage:
  type: sqlite3
  config:
    file: examples/dex.db

# HTTPエンドポイントの設定(HTTPSも可能)
web:
  http: 0.0.0.0:5556

staticClients:
- id: test1
  redirectURIs:
  - 'http://127.0.0.1:5555/callback'
  name: 'Example App'
  secret: skes5xvkplk6vtfnj4unlxldvszxj5ao367qri3eahsn6hwszq

# GRPC APIの設定
grpc:
  addr: 127.0.0.1:5557
  tlsCert: server.crt
  tlsKey: server.key
  tlsClientCA: ca.crt

# Configuration for telemetry (/metrics, /healthz, /healthz/live, /healthz/ready などの監視・metricsエンドポイントの提供)
telemetry:
  http: 0.0.0.0:5558

logger:
  level: "debug"
  format: "text" # can also be "json"

# responseTypeとscopeに関係がある
#   see: https://qiita.com/TakahikoKawasaki/items/4ee9b55db9f7ef352b47
oauth2:
  # response_typeが指定された場合には以下のいずれかにマッチしない場合には未サポート扱いでエラーとなる
  responseTypes: ["code", "token", "id_token"]
#  skipApprovalScreen: true

frontend:
  issuer: dex
  logoURL: theme/logo.png
  dir: web/
  theme: light

connectors:
- type: mockCallback
  id: mock
  name: Example

# Let dex keep a list of passwords which can be used to login to dex.
enablePasswordDB: true

staticPasswords:
- email: "admin@example.com"
  # bcrypt hash of the string "password"
  hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
  username: "admin"
  userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
